import os
import sys
import yaml


def collect(name: str, path: str):
    with open(path) as f:
        cwl = yaml.safe_load(f)
        outputs = cwl["outputs"]
        print("    out:")
        for o in outputs:
            t = outputs[o]["type"]
            print("      - {}".format(o))
        print("## Generated by nsaph/util/cwl_collect_outputs.py from {}:".
              format(os.path.basename(path)))
        for o in outputs:
            t = outputs[o]["type"]
            print("  {}:".format(o))
            print("    type: {}".format(t))
            print("    outputSource: {}/{}".format(name, o))


if __name__ == '__main__':
    collect(sys.argv[1], sys.argv[2])
            